import { useEffect } from "react";

import { listAll } from "@/api/client";
import { getState, patch, set, useApp } from "@/store";
import { scoped } from "@/lib/scope";
import { MON, fmt, todayIso } from "@/lib/format";
import { download, toCsv } from "@/lib/csv";
import { deskNew, deskUrl } from "@/lib/desk";
import {
	PSL_PAYROLL_TYPES, SP_ACTIONS, SP_CAPTURE, SP_PROCESS_FOR, SP_TILES,
	fyList, fyMonths, fyOf,
} from "@/data/payroll";
import { Desk, Gap, Scroll, panelProps, tabProps } from "@/components/ui";

import { PayLegend } from "./shared";

/* Factor HR's SALARY PROCESS, photographed 29 August 2026 on MAR 2026, drawn
   control for control: three lists, the strip of twelve month chips with a "+"
   on the end, the summary line, the six tiles, Generated By / On with Payslip
   Remarks, and then Start Salary Process, Finalize Process and the gear.

   The screen splits cleanly in two, and the split is the honest part of it:

   **Above the summary line it is date arithmetic**, and all of it is live here.
   Which payroll year, which month, what the payroll period is and how many
   calendar days it holds are answerable without reading a single payroll row —
   they are the same twelve months the Payslip screen already walks, off the
   same fyMonths().

   **Below it, it is payroll state**, and none of that is readable: no payroll
   doctype is on the proxy's allowlist and no Payroll Entry has ever run. So the
   tiles are filled from `Employee` where `Employee` can honestly answer, and
   left as a dash where nothing on this side means what the tile means. Two of
   the six are the second kind, and that is a finding rather than a shortfall —
   see SP_TILES.

   The three buttons all write, so all three open on the site. The gear is worth
   more than it looks: it goes to Payroll Settings, where **Consider Unmarked
   Attendance As** decides whether a day the shift job has not processed yet is
   a day's pay gone. CLAUDE.md §5 arriving from the payroll side. */

/** Their date format on the summary line — "01 Mar - 31 Mar 2026". Not `dmy`,
    which writes 01-Mar-2026: this is one line of their screen and it is written
    the way that line writes it, so the two can be read side by side. */
const spanSaid = (a, b) =>
	`${a.getDate().toString().padStart(2, "0")} ${MON[a.getMonth()]} - `
	+ `${b.getDate().toString().padStart(2, "0")} ${MON[b.getMonth()]} ${b.getFullYear()}`;

/** First day, last day and the calendar-day count of a `YYYY-MM`. */
function periodOf(ym) {
	const [y, m] = String(ym).split("-").map(Number);
	const from = new Date(y, m - 1, 1);
	const till = new Date(y, m, 0);
	return { from, till, days: till.getDate(), iso: [ym + "-01", ym + "-" + till.getDate()] };
}

/* One extra read, made the first time somebody opens this screen — not part of
   the load every page pays for.

   `relieving_date` is asked for on its own because their −13 tile is precisely
   the question of whether this site carries it, and a field the site does not
   have would fail the read that draws the whole dashboard if it were added to
   EMP_FIELDS. A refusal is an answer, and it is a different answer from nobody
   having left in the month: the page says which it got. */
async function spProbe() {
	if (getState().spLeftState) return;
	set({ spLeftState: "loading" });

	const rows = await listAll("Employee", ["name", "relieving_date"]).catch(() => null);

	set(rows
		? { spLeft: Object.fromEntries(rows.map((r) => [r.name, r.relieving_date || ""])), spLeftState: "ok" }
		: { spLeft: null, spLeftState: "absent" });
}

/** Who the run would produce a slip for, in the chosen month.

    Employment overlapping the month, not "Active today" — somebody who left on
    the 14th is still owed fourteen days, which is what their tile's "incl. left"
    is about. When `relieving_date` could not be read the rule falls back to
    status and the page says so rather than quietly counting a different
    population: refusing somebody who did work is the expensive mistake, so the
    fallback keeps everybody Active and loses only the part-month leavers. */
function runFor(s, iso) {
	const [start, end] = iso;
	const left = s.spLeft;

	return scoped(s).filter((e) => {
		if (e.date_of_joining && e.date_of_joining > end) return false;
		if (left) {
			const rel = left[e.name];
			return rel ? rel >= start : e.status !== "Left";
		}
		return e.status === "Active";
	});
}

/** One tile. `n` is the figure, `s` the small print under the label, and a null
    `n` is drawn as a dash with the reason on it — the two tiles nothing here
    can mean are the point of the strip, not a gap in it. */
function SpTile({ label, sub, n, why, warn }) {
	return (
		<div className={"sptile" + (n == null ? " dead" : "") + (warn ? " warn" : "")} title={why}>
			<span className="k">
				{label}
				{sub ? <small> {sub}</small> : null}
			</span>
			<b className="n">{n == null ? "—" : n}</b>
		</div>
	);
}

/** What this screen can honestly put in a file: who the chosen month's run
    would cover, and whether each of them has the two things that decide their
    payment days. Not a payroll file — there is no amount on this side to put
    in one, and the heading row says so. */
function spCsv(rows, ym, s) {
	const cols = ["Employee code", "Name", "Company", "Status", "Joined", "Relieved",
		"Holiday list", "Month"];
	download(
		"salary-process-" + ym + ".csv",
		toCsv(cols, rows.map((e) => [
			e.employee_number || e.name,
			e.employee_name || "",
			e.company || "",
			e.status || "",
			e.date_of_joining || "",
			(s.spLeft && s.spLeft[e.name]) || "",
			e.holiday_list || "",
			ym,
		])),
	);
}

export default function SalaryProcess() {
	const s = useApp();
	const f = s.sp;

	/* Read once, on arrival. Every other screen pays nothing for it. */
	useEffect(() => { void spProbe(); }, []);

	/* Both resolved at render rather than seeded in the store: this is the one
	   screen where the month decides what everybody is paid, and a default fixed
	   at module load is a default that is wrong for anybody who left the tab open
	   over a month end. */
	const year = f.year || fyOf(todayIso());
	const months = fyMonths(year);
	const now = todayIso().slice(0, 7);
	/* Their capture had the last month of the chosen year selected while the
	   clock was well past it, which is what a year you are no longer in looks
	   like. Same rule here: this month if it is in this year, otherwise the last
	   one that is. */
	const month = f.month && months.some(([ym]) => ym === f.month)
		? f.month
		: (months.some(([ym]) => ym === now) ? now : months[months.length - 1][0]);

	const per = periodOf(month);
	const [start, end] = per.iso;
	const label = (MON[Number(month.slice(5, 7)) - 1] + " " + month.slice(0, 4)).toUpperCase();

	const run = runFor(s, per.iso);
	const joined = run.filter((e) => e.date_of_joining >= start && e.date_of_joining <= end);
	const leftIn = s.spLeft
		? run.filter((e) => {
			const rel = s.spLeft[e.name];
			return rel && rel >= start && rel <= end;
		})
		: null;

	/* The two things that decide payment days, and both are the blocker rather
	   than a detail of it: without a holiday list a week-off is a working day
	   that nobody worked, and without Attendance there is nothing to divide the
	   month by at all. */
	/* "Could not be read" and "still reading" are different answers, and the
	   tile is the one place somebody looks for the second one. */
	const leftWhy = leftIn
		? `${leftIn.length} left in ${label}, off relieving_date`
		: s.spLeftState === "loading"
			? "Reading relieving_date…"
			: "relieving_date could not be read on this site, so leavers in the month cannot be counted"
				+ " — see the note under the screen.";

	const noList = run.filter((e) => !e.holiday_list);
	const att = s.counts.attendance || 0;
	const lists = s.counts.holiday || 0;

	const value = {
		total: fmt(run.length),
		pending: fmt(run.length),
		process: "0 / " + fmt(run.length),
		stopsal: null,
		stoppay: null,
		arrears: null,
	};

	return (
		<>
			<PayLegend what="Salary Process">
				The monthly run. In Frappe HR it is <code>Payroll Entry</code> → <code>Salary Slip</code>,
				and it is stock — which is not the same as it being ready. Their screen is drawn below as
				photographed; <b>nothing on this side runs a payroll.</b>
			</PayLegend>

			<div className="fhscreen">
				<div className="spbar">
					<span className="adf">
						<label htmlFor="sp-year">Year</label>
						{/* Live. A payroll year is April to March and the label is theirs. */}
						<select id="sp-year" value={year}
							title="April to March, written the way their box writes it. Live — it is arithmetic on the clock, not a payroll read."
							onChange={(e) => patch("sp", { year: e.target.value, month: "" })}>
							{fyList(todayIso()).map((y) => <option key={y}>{y}</option>)}
						</select>
					</span>
					<span className="adf">
						<label htmlFor="sp-type">Payroll Type</label>
						{/* The same control their Payslip screen carries, and the same single
						    value — so it reuses that list rather than declaring a second one
						    which could drift from it. */}
						<select id="sp-type" disabled value={f.ptype}
							title="Monthly was the value in the capture, on this screen and on their payslip form. Neither list has been opened, so one value is all this offers."
							onChange={() => {}}>
							{PSL_PAYROLL_TYPES.map((t) => <option key={t}>{t}</option>)}
						</select>
					</span>
					<span className="adf">
						<label htmlFor="sp-for">Process For</label>
						<select id="sp-for" disabled value={f.pfor}
							title="All Employees was the value in the capture and the list was never opened. On our side the same idea is the filters on a Payroll Entry — branch, department, designation — which choose who the run covers."
							onChange={() => {}}>
							{SP_PROCESS_FOR.map((t) => <option key={t}>{t}</option>)}
						</select>
					</span>
				</div>

				{/* Their month strip, April first — payroll order, not calendar order. */}
				<Scroll>
					<div className="spmonths" role="tablist" aria-label="Payroll month">
						{months.map(([ym, name]) => {
							const on = ym === month;
							/* A month that has not finished cannot be run, and their screen
							   makes no distinction — ours says it in a tooltip rather than by
							   refusing the click, because looking at next month is not the
							   mistake; paying it is. */
							const ahead = ym > now;
							return (
								<button key={ym} {...tabProps("spm-" + ym, "sp-panel", on)}
									className={"spm" + (on ? " on" : "") + (ahead ? " ahead" : "")}
									title={ahead ? name + " has not happened yet." : name}
									onClick={() => patch("sp", { month: ym })}>
									<b>{MON[Number(ym.slice(5, 7)) - 1].toUpperCase()}</b>
									<small>{ym.slice(0, 4)}</small>
								</button>
							);
						})}
						{/* Their "+". Never pressed, so what it adds is unknown — an extra
						    off-cycle period is the obvious reading and it is only a reading,
						    so nothing is invented behind it. */}
						<button className="spm add" disabled
							title="Their +, which has never been pressed. What it adds is unknown and nothing is invented in its place.">
							+
						</button>
					</div>
				</Scroll>

				<div className="sppanel" {...panelProps("sp-panel", "spm-" + month)}>
					<div className="spsum">
						<b>{label}</b>
						<span>
							<i>Payroll date:</i> {spanSaid(per.from, per.till)} | Calendar days {per.days}
						</span>
						{/* Two ranges on their line, and identical in the capture. They are
						    separate controls there, which is how a cut-off other than the
						    month end gets said — 26th to 25th, say. A Payroll Entry has one
						    period for both, so a cut-off would be a custom field and a change
						    to how attendance is counted, not a setting. */}
						<span title="Identical to the payroll date in their capture. Theirs are two separate ranges, which is how an attendance cut-off other than the month end would be said; a Payroll Entry has one period for both.">
							<i>Attendance date:</i> {spanSaid(per.from, per.till)} | Calendar days {per.days}
						</span>
						<span className="st" title="No Payroll Entry has ever run on this site, so every month reads the same. Not a filter that found nothing.">
							<i>Status:</i> NOT GENERATED
						</span>
					</div>

					<div className="sptiles">
						<SpTile label="Total employees" sub="(incl. left)" n={
							<>
								{value.total}
								<em className="up" title={`${joined.length} joined in ${label}, off date_of_joining`}>
									+{joined.length}
								</em>
								<em className="dn" title={leftWhy}>
									{leftIn ? "−" + leftIn.length : (s.spLeftState === "loading" ? "−…" : "−?")}
								</em>
							</>
						} why={SP_TILES[0].why} />
						{SP_TILES.slice(1).map((t) => (
							<SpTile key={t.k} label={t.label} sub={t.sub} n={value[t.k]} why={t.why}
								warn={!t.map} />
						))}
					</div>
					</div>

				<div className="spgen">
					<span><i>Generated By:</i> —</span>
					<span><i>Generated On:</i> —</span>
					<label htmlFor="sp-rem"><i>Payslip Remarks:</i></label>
					<input id="sp-rem" disabled value={f.remarks} onChange={() => {}}
						title="A note carried onto the run. Nothing here writes payroll, so there is nothing for it to be carried onto — it is written against the Payroll Entry, on the site." />
				</div>

				<div className="spacts">
					<b className="font-display">Salary Process</b>
					<Desk className="embtn pri" href={s.site && deskNew(s.site, "Payroll Entry")}
						label="Start Salary Process" title={SP_ACTIONS[0][2]}>
						Start Salary Process
					</Desk>
					{/* Their split caret, which has never been opened. */}
					<button className="embtn pri split" disabled aria-label="Start options"
						title="Their caret, never opened. What it offers is unknown and nothing is invented in its place.">
						▾
					</button>
					<Desk className="embtn pri" href={s.site && deskUrl(s.site, "Payroll Entry")}
						label="Finalize Process" title={SP_ACTIONS[1][2]}>
						Finalize Process
					</Desk>
					<Desk className="embtn gear" href={s.site && deskUrl(s.site, "Payroll Settings")}
						label="Payroll settings" title={SP_ACTIONS[2][2]}>
						⚙
					</Desk>
					<button className="embtn spexp" onClick={() => spCsv(run, month, s)}
						title="Export who this month's run would cover, with the two fields that decide their payment days. Not a payroll file — there is no amount on this side to put in one.">
						Export the run
					</button>
				</div>
			</div>

			<div className="mt-[1rem]">

				<div className="mt-[.7rem]">
					{att ? null : (
						<Gap>
							<b>There is no <code>Attendance</code> on this site at all</b>, and payment days are
							computed from it. Until the shift job is generating attendance from punches, a
							Payroll Entry has nothing to divide the month by — every slip it produced would be a
							full month for everybody, including the people who were not there. This is the
							blocker under this screen, and it is an attendance blocker rather than a payroll one.
						</Gap>
					)}
				</div>

				<div className="mt-[.7rem]">
					{noList.length ? (
						<Gap>
							<b>{fmt(noList.length)} of {fmt(run.length)} people in this run have no{" "}
							<code>holiday_list</code></b>. Without one, a week-off and a public holiday are
							working days that nobody worked, and the run takes the pay for them off somebody who
							was never expected in. {fmt(lists)} holiday{lists === 1 ? " list exists" : " lists exist"}{" "}
							on the site; what is missing is the assignment, not the list.
						</Gap>
					) : null}
				</div>

				{s.spLeftState === "absent" ? (
					<div className="mt-[.7rem]">
						<Gap>
							<b><code>relieving_date</code> could not be read</b>, so the leavers half of their
							first tile is a question mark rather than a number, and this run counts everybody
							Active instead of everybody employed during the month. That loses the part-month
							leavers — the people their &ldquo;incl. left&rdquo; is there for. It is the safe
							direction to be wrong in on a screen that cannot pay anybody, and it is the wrong
							one the day it can.
						</Gap>
					</div>
				) : null}

				<div className="mt-[.7rem]">
					<Gap>
						<b>Stop Salary and Stop Payment have no equivalent here.</b> Frappe HR ships no flag on{" "}
						<code>Employee</code> or <code>Salary Slip</code> that holds one person out of a run,
						and the two are not the same hold — one stops the salary, the other stops only the
						payment of a slip that still generates. Both are a custom field plus a rule inside the
						run, and both were zero in the capture, so nobody can say yet how often they are used.
					</Gap>
				</div>

			</div>
		</>
	);
}
